### ISSUE TITLE
Use HAML instead of erb

### ISSUE THREAD

**Issue by bion** [scottmacphersonmusic/bookmarker#4]
:point_right: http://haml.info/ :point_left: 

there's also a [gem for converting your erb to HAML](https://github.com/dhl/erb2haml) for you so you don't have to do it by hand. doing it by hand is probably a good way to learn it, though.

**Comment by scottmacphersonmusic** [comment]
https://gist.github.com/scottmacphersonmusic/a266a89ea3df4fdff517
