### ISSUE TITLE
ensure no XSS vulnerability with link URLs

### ISSUE THREAD

**Issue by bion** [scottmacphersonmusic/bookmarker#7]
https://en.wikipedia.org/wiki/Cross-site_scripting

**Comment by scottmacphersonmusic** [comment]
I'm having some trouble with this one.  It sounds like in versions 3 and later of Rails all form inputs are 'sanitized' via html escaping.  If this takes care of making sure users can't input javascript what else should I be protecting against?

**Comment by bion** [comment]
Make sure it's safe by writing an acceptance test that asserts everything gets escaped properly. Use [capybara](https://github.com/jnicklas/capybara).
